%% Optimization of Soft Actuator
clear all;
close all;
clc;
% This m file aims to preliminary check the torque and bending angle
% generated by the optimal parameters from
% "OptimizedDesignofSPA_Torque_Bending_Controllability" before
% fabrications.

%% Optimal parameters
b = 0.02; % m
a = 0.004; % m
t = 0.0015; % m
w = 0.03; % m
L = 0.094; % m
E = 340000; % Pa
P = 0.15*1000000; % Pa

%% Pressure-to-Torque model
f1 = 0.5*P*(b-t)*(b-t)*(w-2*t);
f2 = ((b-t)*(w-2*t)*P)/(a*w+w*t+2*b*t-2*t^2);
f3 = 0.5*(w*a^2-(w*t)*(2*b-t)-2*t*(b-t)*(b-t));
C = (f1+f2*f3)/P; % C is used in pressure-to-bending model
torque = C*P;


%% Pressure-to-Bending model
n = 1.0; % power of elongation term (1.0~1.8 depends on the material properties)
In = (0.5)^(1+n)*(1/(2+n))*w*(a+b)^(2+n)
I = (1/12)*w*(a+b)^3
A = (w-2*t)*(b-t);
Aw = (w*(a+b))-A;

theta = 0.5*(((L*C*P)/(E*I))+(((A-Aw)*L*C*P*P)/(Aw*E*E*I)))*180/pi
theta_n = (((n/(n+1))^n*(C*P/(E*In))*(L+(L*P*(A-Aw)/(Aw*E)))^n))^(1/n)*180/pi


%% Natural frequency
M = 0.36;
wn = (((n+1)/n)^n*((E*In)/(M*L^(n+1))))^0.5
